name: Deploy PrinterAgent

on:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: self-hosted

    steps:

      - name: Checkout Latest Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
         python -m venv .venv
          .\.venv\Scripts\python.exe -m pip install --upgrade pip
          .\.venv\Scripts\python.exe -m pip install -r requirements.txt
      - name: Verify Syntax
        run: |
          python -m py_compile app.py

      - name: Restart PrinterAgent Service
        run: |
          nssm restart PrinterAgent